
<!-- Page content-->
<div class="container-fluid" xmlns="">
    <h1 class="mt-4 text-center">Where Are My Friends?</h1>
</div>

<div class="container-fluid justify-content-center ">
    <div id="map" class="map mr-sm-5" style="width: 100%; height: 700px"></div>
    <div id="popup" class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer"></a>
        <div id="popup-content"></div>
    </div>
    <p class="" id="timer"></p>
    <a class="align-items-end" href="https://www.flaticon.com/free-icons/location" title="location icons">Location icons created by IconMarketPK - Flaticon</a>
</div>

<script src="../../v6.14.1/build/ol.js"></script>
<script src="../js/map.js"></script>
<script src="../AJAX/getFriendLoc.js"></script>




