<?php require('template/header.phtml') ?>
<!-- Page content-->
<div class="container-fluid">
    <h1 class="mt-4 text-center">Log In or Sign Up</h1>
</div>


<!--Albumn to contain cards-->
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <!--card to log in form-->
                <div class="card mb-6 box-shadow">
                    <div class="card-body">
                        <h4 class="text-center">Please enter your login details</h4>
                        <br>
                        <div class="d-flex justify-content-center">
                            <form method="post" action="" class="form">
                                <div class="form-group row pb-2">
                                    <label for="usernameLogIn" class="h5 col-sm-5">Email:</label>
                                    <div class="col-sm-5">
                                        <input type="text" name="usernameLogIn">
                                    </div>
                                </div>

                                <div class="form-group row pb-2">
                                    <label for="passwordLogIn" class="h5 col-sm-5">Password:</label>
                                    <div class="col-sm-5">
                                        <input type="text" name="passwordLogIn">
                                    </div>
                                </div>

                                <div class="form-group row pb-2">
                                    <label for="humanLogIn" class="col-sm-10">I confirm that I am a human</label>
                                    <div class="col-sm-1">
                                        <input type="checkbox" name="humanLogIn">
                                    </div>
                                </div>

                                <div class="d-flex justify-content-end pb-2">
                                    <input type="submit" name="loginbutton" value="Login" class="btn btn-outline-dark">
                                </div>

                                <div class="form-group row pb-2 pt-2 text-warning">
                                    <p><b>
                                        <?php
                                        //returns login error if it exists
                                        if (isset($_SESSION['errorLogIn'])){
                                            echo $_SESSION['errorLogIn'];
                                        }
                                        ?>
                                        </b>
                                    </p>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

            <?php require('Views/register.phtml') ?>
        </div
    </div>
</div>

<?php require ('template/footer.phtml') ?>

