<?php require("Views/template/header.phtml") ?>
<!-- Page content-->
<div class="container-fluid">
    <h1 class="mt-4 text-center">Profile View</h1>
</div>

<?php
//var_dump($_SESSION['selectedID']);
if (isset($_SESSION['selectedID'])) {
    $selectedID = $_SESSION['selectedID'];
    $view->userDataSet = $userDataSet->fetchUserByID($selectedID);
    require_once('Views/displayProfile.phtml');
}
?>


<?php require('template/footer.phtml') ?>
